#!/bin/bash

test $1 = "init"

if [ $? ]
then
  mkdir /etc/smec
  cd /etc/smec
  git clone https://github.com/semissioncontrol/repos
  mkdir src
  exit 0
fi

test $1 = "install"

if [ $? ]
then
  echo "Searching repositories for $2"
  
  cd /etc/smec/repos
  
  if [[ $(find -iname '$2*.smec') ]]
  then
    echo "$2 found."
    CATEGORY=find -iname '$2*.smec' | cut -d "/" -f 3
    PACKAGE=find -iname '$2*.smec' | cut -d "/" -f 4
    cd /etc/smec/src/
    mkdir ${CATEGORY}/${PACKAGE}
    cd ${CATEGORY}/${PACKAGE}
    REPO=../../../../../repos/${CATEGORY}/${PACKAGE} VERSION=2.9 bash ../../../repos/${CATEGORY}/${PACKAGE}-${VERSION}
    # todo here ^: fix the many ..'s in REPO, and a globally working VERSION var
  else
    echo "$2 not found."
    exit 1
  fi
  
fi
